import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/Provider/ThemeProvider";
import  AbstraxionProviderWrapper  from "@/Provider/AbstraxionProvider";
import { Inter } from 'next/font/google'
import { Toaster } from "react-hot-toast";


const treasuryConfig = {
  treasury: process.env.NEXT_PUBLIC_TREASURY_ID,
  rpcUrl: "https://rpc.xion-testnet-2.burnt.com/",
  restUrl: "https://api.xion-testnet-2.burnt.com/"
};

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "X-Chat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem={false}  disableTransitionOnChange>
        <AbstraxionProviderWrapper>
          {children}
          <Toaster/>
        </AbstraxionProviderWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
